[package]
name = "adventofcode2018"
version = "0.1.0"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
chrono = "0.4"

[lib]
name = "aoc"
path = "src/lib.rs"